language: ruby
addons:
  postgresql: "9.4"
rvm:
 - "2.2.3"
cache: bundler
before_script:
  - "for i in config/*.example; do cp \"$i\" \"${i/.example}\"; done"
  - bundle exec rake db:setup
  - bundle exec rake parallel:create parallel:prepare
script: bundle exec rake parallel:test
