files:
  - source: /config/locales/en/**.yml
    translation: /config/locales/%locale%/%original_file_name%
    languages_mapping:
      locale:
        es-ES: es
        fr: fr
        nl: nl
        pt-PT: pt
        ca-ES: ca
        gl-ES: gl
        ast-ES: ast
        he-IL: he
        it-IT: it
        ru-RU: ru
