files:
  - source: /config/locales/custom/es/**.yml
    translation: /config/locales/custom/%locale%/%original_file_name%
    languages_mapping:
      locale:
        en: en
        ast: ast
        ca: ca
        eu-ES: eu
        fr: fr
        gl: gl
        val-ES: val
