files:
  - source: /config/locales/en/**.yml
    translation: /config/locales/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BT
        es-PE: es-PE
