version: '3'
services:
  database:
    image: postgres:9.4.5
    volumes:
      - docker-example-postgres:/var/lib/postgresql/data

  app:
    build: .
    image: consul-app
    entrypoint: /usr/local/bin/entrypoint.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    working_dir: /var/www/consul
    environment:
      - NEW_RELIC_AGENT_ENABLED=false
      - DATABASE_HOST=database
      - DATABASE_NAME=postgres
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/consul:delegated
      - bundle:/usr/local/bundle:delegated

  migration:
    image: consul-app
    environment:
      - DATABASE_HOST=database
      - DATABASE_NAME=postgres
    command: bin/rake db:migrate
    volumes:
      - .:/var/www/consul:delegated
      - bundle:/usr/local/bundle:delegated
    depends_on:
      - app
      - database

  prepare:
    image: consul-app
    command: bash -c "bin/rake db:create && bin/rake db:migrate && bin/rake db:seed && bin/rake db:dev_seed"
    environment: 
      - DATABASE_HOST=database
      - DATABASE_NAME=postgres
    volumes:
      - .:/var/www/consul:delegated
      - bundle:/usr/local/bundle:delegated
    depends_on:
      - app
      - database

volumes:
  docker-example-postgres: {}
  bundle: {}

