User:
  fields:
    id:       integer
    username: string
Voter:
  options: [disable_filtering]
  fields:
    gender:     string
    age_range:  string
    geozone_id: integer
    geozone:    Geozone
Debate:
  fields:
    id:                 integer
    title:              string
    description:        string
    created_at:         string
    cached_votes_total: integer
    cached_votes_up:    integer
    cached_votes_down:  integer
    comments_count:     integer
    hot_score:          integer
    confidence_score:   integer
    geozone_id:         integer
    geozone:            Geozone
    comments:           [Comment]
    public_author:      User
Proposal:
  fields:
    id:                   integer
    title:                string
    description:          string
    external_url:         string
    cached_votes_up:      integer
    comments_count:       integer
    hot_score:            integer
    confidence_score:     integer
    created_at:           string
    summary:              string
    video_url:            string
    geozone_id:           integer
    retired_at:           string
    retired_reason:       string
    retired_explanation:  string
    geozone:              Geozone
    comments:             [Comment]
    proposal_notifications: [ProposalNotification]
    public_author:        User
Comment:
  fields:
    id:                 integer
    commentable_id:     integer
    commentable_type:   string
    body:               string
    created_at:         string
    cached_votes_total: integer
    cached_votes_up:    integer
    cached_votes_down:  integer
    ancestry:           string
    confidence_score:   integer
    public_author:      User
Geozone:
  fields:
    id:               integer
    name:             string
ProposalNotification:
  fields:
    title:            string
    body:             string
    proposal_id:      integer
    created_at:       string
    proposal:         Proposal
Tag:
  fields:
    id:               integer
    name:             string
    taggings_count:   integer
    kind:             string
Vote:
  fields:
    votable_id:       integer
    votable_type:     string
    public_timestamp: string
    public_voter:     Voter
