default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development: &development
  <<: *default
  database: development

production:
  <<: *default
  database: production

test:
  <<: *default
  database: test
