- 
  - Ciutat Vella
  - 1
- 
  - Eixample
  - 2
- 
  - Sants Montjuïc
  - 3
- 
  - Les Corts
  - 4
- 
  - Sarrià - Sant Gervasi
  - 5
- 
  - Gràcia
  - 6
- 
  - Horta - Guinardó
  - 7
- 
  - Nou Barris
  - 8
- 
  - Sant Andreu
  - 9
- 
  - Sant Martí
  - 10
