name: Init new consul
on: 
  workflow_dispatch:
    inputs:
      target_environment:
        type: choice
        description: Choose the environment
        options:
        - ConsulNL
        - Leeuwarden

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: 
      name: ${{ inputs.target_environment }}
    
    steps:
    - id: sets-a-secret
      name: Printing stuff
      run: |
        echo "${{ inputs.target_environment }}"
    
    - name: Install Ansible
      run: sudo apt install ansible

    - name: Clone installer repository
      uses: actions/checkout@v2
      with:
        repository: consul/installer
        path: installer
        
    - name: Create hosts
      working-directory: ./installer
      run: sed -e "s/remote-server-ip-address/$REMOTE_IP/" -e "s/root/$ANSIBLE_USER/" hosts.example > hosts
      
    - name: Run playbook
      working-directory: ./installer
      run: ansible-playbook -v consul.yml -i hosts
